### ISSUE TITLE
来杭州找工作

### ISSUE THREAD

**Issue by 5Mi** [5Mi/wumi_blog#72]
>记录下这几天，这些经历
五月九日 周二出发 298车票
五月十日 周三到 上城区转了一天 80住宿
五月十一 周四 中午坐车到仓前梦想小镇，走了一下午找了个住的地方 110
五月十二 周五 上午下雨，今天中午终于得到次面试的机会，但总估计希望不大，下午想着能再面试一家走了挺远也没接电话，得下周一去看看，又在这续住了一天110 中午吃饭兰州风味花了12
五月十三 周六 去网吧调查了下感觉不靠谱就又续住了两天老板给便宜了十块，两天200今儿干了一天游戏，中午吃兰州花了9
五月十四 周日 今天下午学习啦虽然效率不高，中午兰州花了9，之后买泡面洗发水花了21.3
五月十五 周一 面试成功了一发但初创公司工资8.5k很遗憾，唉续住又花了100
五月十六 周二 今天又是杳无音信的一天，充话费50，回上城区住80，下午小碗拉面9，坐车算上之前的8
五月十七，周三 续住80 泡面4.5 逛了西湖坐车2，晚饭5
五月十八，周四 续住80 水2 今天面试了3家有一家是傻逼，还收到了不少面试，安排在明后天~ 坐车8 晚上面包9
五月十九，周五 续住80 今天面了4家，不知道下文怎么样，坐车11.5 水1.5
五月二十，周六 续住80 坐车4 鱼香肉丝盖饭13 泡面肥皂8.5 话费50 面了一家等了俩点儿不知道靠不靠谱
五月二一 周日 续住80 面包泡面8
五月二二 周一 续住80 坐车8 今儿去同花顺面试了感觉加班有点儿多 晚上吃饭 俩盖饭23
五月二三 周二 住70坐车2.5 下了一天的雨，不知道走到今天这步是对是错吃饭11
五月二四 周三 续住70吃饭58
目前16天，花销1958

五月一放假后在家休息了好久,把取公积金办完又在家玩了几天陪陪媳妇儿,9号出发

找工作那几天挺煎熬的天天到处跑,挑便宜的地方,每天早上就得考虑要不要转移或者续住,只有支出没收入,独自一人

找到工作不知道该说困难还是顺利,好歹凭两年工作经验和准备找到了工作,一开始都没什么面试,但只要去了面试一般还是能收到offer的
![](https://raw.githubusercontent.com/5Mi/markdown-images/master/images/IMG_20170608_222454.jpg)

最后出于印象的好坏选择了这家公司,感觉自己对人与人的感受不会欺骗我,确实,新公司的小伙伴们都很年轻,人都不错,还算合得来,一个个同龄人感觉都比自己强好多,但24号上班以来几乎每天都加班到八九点,确实比以前累不少,每天神经都绷得很紧,一集中就是一整天.新人刚开始累点很正常,但这几天的累都有些许不合理,交给我的任务需求需要靠之前源码来目测理解,把之前的jq改用react重新实现并且改逻辑,但里面的业务逻辑和接口我都不知道也没接口文档,都得靠读源码来搞,一步步自己调试,举步维艰,费劲不在技术上= =,压力不小.

但工作不好找,既然来了转正就是短期目标了,不管之后是去是留都得先做好工作转正了再说,说到这,这些天又迷茫起来了,自己走下来的路到底对不对呢,有时候觉得还不错,有时候又觉得自己不是这块料,适不适合自己也拿不准.

有时候有好多话没人倾诉,也没指望谁来看,写在这里权当排遣,在就是供将来的自己思考,自己到底是怎么一步步走到今天这里的.妈的,明明算走了技术路线,但相比别人写技术blog,我还是倾向写这些啊,也是挺没出息的,长叹一声,想到哪写到哪,也不知道写了些什么

**Comment by nickwongwong** [comment]
楼主用issue写blog很有创意呀
